# Trigger on push to master (+ allow manual runs of this workflow)
# First job: identical steps to PR workflow
# Second job: Deploy to Heroku

name: on-merge-workflow

on:
  push:
    branches:[master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
          uses: actions/setup-node@v3
            with: '14'
      - name: run tests
          run: npm install
          run: npm test
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku 
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  
        with:
          email: roniana11@gmail.com
          api_key: secrets.API-
          app_name: secrets.USER
          dockerfile_path: '..'
